sudo: false
language: node_js
node_js:
  - "4"
before_script:
  - npm run initdb-test
script:
  - npm test
  - npm run coverage
  - npm run publish-coverage
notifications:
  slack: standardanalytics:vPQA8IowAphWwzDgGtHkdkRk
